### ISSUE TITLE
index out of range when checking notifications

### ISSUE THREAD

**Issue by nate-double-u** [mikerhodes/github-to-omnifocus#10]
Hi, i've been getting the following error when I have unread notifications:

```
panic: runtime error: index out of range [-3]

goroutine 1 [running]:
github.com/USERNAME/github-to-omnifocus/internal/gh.(*GitHubGateway).GetNotifications(0xc000493a58)
        /Users/USERNAME/Repos/personal/github-to-omnifocus/internal/gh/github.go:166 +0x95d
main.GetGitHubState({{0x1316a50, 0xc0000160b0}, 0xc000166000})
        /Users/USERNAME/Repos/personal/github-to-omnifocus/cmd/github2omnifocus/main.go:181 +0xfb
main.main()
        /Users/USERNAME/Repos/personal/github-to-omnifocus/cmd/github2omnifocus/main.go:71 +0x58c
```

Unfortunately I don't know much GoLang, or much about the GitHub API, so I thought I'd report it as a bug and see if there was anyone else experiencing the same thing.

**Comment by mikerhodes** [comment]
Hmm odd. I have this running myself with notifications and I've not seen the issue. This is happening every time you run github-to-omnifocus, and do notifications make it at all into Omnifocus itself?

**Comment by nate-double-u** [comment]
It's actually sorted itself out -- so I imagine it was probably an issue with the API (though, it probably wouldn't hurt to put an out of bounds check on that response)

**Comment by nate-double-u** [comment]
(while I'm here -- thanks for building this, it's a super useful tool 🙂)

**Comment by mikerhodes** [comment]
🤞 it stays working! And I'm glad it's more than just me using this!

**Comment by yeled** [comment]
can I re-open? I can replicate this


```

[..]

2023/05/22 20:58:40 Getting Notifications page 149
2023/05/22 20:58:40 Getting Notifications page 150
panic: runtime error: index out of range [-3]

goroutine 1 [running]:
github.com/mikerhodes/github-to-omnifocus/internal/gh.(*GitHubGateway).GetNotifications(0xc000267428)
	/Users/yeled/src/github-to-omnifocus/internal/gh/github.go:166 +0x8f8
main.GetGitHubState({{0x136ede8, 0xc000018178}, 0xc000002180})
	/Users/yeled/src/github-to-omnifocus/cmd/github2omnifocus/main.go:181 +0xdb
main.main()
	/Users/yeled/src/github-to-omnifocus/cmd/github2omnifocus/main.go:71 +0x5c5
make: *** [run] Error 2```

**Comment by mikerhodes** [comment]
Reopening the issue.

@yeled I assume this happens every time? Have you been able to debug what's happening, like a particular notification?

Looking at the code, seems like I need to be more defensive here (sounds like there is no URL for this notification) but I'd like to understand what's coming off the wire if I can, as otherwise I think the fix is going to be adding a guard for the length of `parts` and skipping items where they are too short. If I know what the notification is, perhaps there's a better solution than skipping.

https://github.com/mikerhodes/github-to-omnifocus/blob/fb3907198b6af9e34f0c99b14414f95422a80a25/internal/gh/github.go#L163-L166

**Comment by yeled** [comment]
Looks like the troublesome notification has no `baseUrl` ?

I added `log.Printf("lp: %s", lp)` and `log.Printf("parts: %s", notification.Subject)`

```
2023/05/26 11:30:33 parts: &{%!s(*string=0xc0000e87e0) %!s(*string=0xc0000e87f0) %!s(*string=0xc0000e8800) %!s(*string=0xc0000e8810)}
2023/05/26 11:30:33 lp: %!s(int=8)
2023/05/26 11:30:33 parts: &{%!s(*string=0xc0000e8be0) %!s(*string=0xc0000e8bf0) %!s(*string=0xc0000e8c00) %!s(*string=0xc0000e8c10)}
2023/05/26 11:30:33 lp: %!s(int=8)
2023/05/26 11:30:34 parts: &{%!s(*string=0xc0000e8fe0) %!s(*string=0xc0000e8ff0) %!s(*string=0xc0000e9000) %!s(*string=0xc0000e9010)}
2023/05/26 11:30:34 lp: %!s(int=8)
2023/05/26 11:30:34 parts: &{%!s(*string=0xc0000e93f0) %!s(*string=0xc0000e9400) %!s(*string=<nil>) %!s(*string=0xc0000e9410)}
2023/05/26 11:30:34 lp: %!s(int=8)
2023/05/26 11:30:35 parts: &{%!s(*string=0xc0000e97f0) %!s(*string=0xc0000e9800) %!s(*string=<nil>) %!s(*string=0xc0000e9810)}
2023/05/26 11:30:35 lp: %!s(int=8)
2023/05/26 11:30:35 parts: &{%!s(*string=0xc0000e9bf0) %!s(*string=0xc0000e9c00) %!s(*string=0xc0000e9c10) %!s(*string=0xc0000e9c20)}
2023/05/26 11:30:35 lp: %!s(int=8)
2023/05/26 11:30:36 parts: &{%!s(*string=0xc0000ec000) %!s(*string=0xc0000ec010) %!s(*string=0xc0000ec020) %!s(*string=0xc0000ec030)}
2023/05/26 11:30:36 lp: %!s(int=8)
2023/05/26 11:30:36 parts: &{%!s(*string=0xc0000ec400) %!s(*string=0xc0000ec410) %!s(*string=0xc0000ec420) %!s(*string=0xc0000ec430)}
2023/05/26 11:30:36 lp: %!s(int=8)
2023/05/26 11:30:36 parts: &{%!s(*string=0xc0000ec810) %!s(*string=0xc0000ec820) %!s(*string=0xc0000ec830) %!s(*string=0xc0000ec840)}
2023/05/26 11:30:36 lp: %!s(int=8)
2023/05/26 11:30:37 parts: &{%!s(*string=0xc0000ecc20) %!s(*string=0xc0000ecc30) %!s(*string=0xc0000ecc40) %!s(*string=0xc0000ecc50)}
2023/05/26 11:30:37 lp: %!s(int=8)
2023/05/26 11:30:37 parts: &{%!s(*string=0xc0000ed020) %!s(*string=0xc0000ed030) %!s(*string=0xc0000ed040) %!s(*string=0xc0000ed050)}
2023/05/26 11:30:37 lp: %!s(int=8)
2023/05/26 11:30:37 parts: &{%!s(*string=0xc0000ed430) %!s(*string=<nil>) %!s(*string=<nil>) %!s(*string=0xc0000ed440)}
2023/05/26 11:30:37 lp: %!s(int=1)
panic: runtime error: index out of range [-3]
```

**Comment by yeled** [comment]
some debugging with `curl` and I've found a notification without an URL:


```json
  {
    "id": "65666XXXXX",
    "unread": true,
    "reason": "ci_activity",
    "updated_at": "2023-05-25T12:53:55Z",
    "last_read_at": null,
    "subject": {
      "title": "some text blah blah",
      "url": null,
      "latest_comment_url": null,
      "type": "CheckSuite"
    },
    "repository": {
        [...]
    },
    "url": "https://api.github.com/notifications/threads/6566XXXXXX",
    "subscription_url": "https://api.github.com/notifications/threads/65666XXXXXX/subscription"
  },
```

**Comment by mikerhodes** [comment]
Thanks for digging in! 

So this looks like a subscription to check results. I didn't know you could do that. 

I use the subject URL to uniquely identify a given task, to make sure we don't duplicate it in Omnifocus (as well as, obviously, including the link in the note). I think we can use the `notifications/threads/6566XXXXXX` as the unique ID for these notifications (to deduplicate), but there doesn't seem to be a useful URL to send the user to in this notification (perhaps there is a way to map the `api.github.com` URL to the HTML URL you know of?)

For you personally, would it make sense to include this notification in Omnifocus or to ignore it? Even without the URL (which makes it hard to visit the notification to dismiss it).

**Comment by yeled** [comment]
> For you personally, would it make sense to include this notification in Omnifocus or to ignore it? Even without the URL (which makes it hard to visit the notification to dismiss it).

Personally I dislike having CI in my notifications. I'd ignore it for now until GitHub has a clearer view on how it's mean to be handled.

**Comment by mikerhodes** [comment]
I added a quick check that we have enough parts for parsing to continue; please try out `master`/`v2.4`.

**Comment by yeled** [comment]
looks good. great idea re: parts. I'll run it for a few days, I don't currently have any `ci_activity` in my Notifications.

**Comment by nate-double-u** [comment]
Thanks @mikerhodes & @yeled!
